spring.application.name=GigGuide

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/gig_guide_db
spring.datasource.username=postgres
spring.datasource.password=@Londi45
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
